# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

production:
  secret_key_base: 3b6e41b2a5e5d7852616117616ceec851e0982390a9d8d39654fcba6525eccaf99ceb9062a384bfae040d34f5408ca505c0ded68f525dc26cf7a611f56e0b9af 
development:
  secret_key_base: 3b6e41b2a5e5d7852616117616ceec851e0982390a9d8d39654fcba6525eccaf99ceb9062a384bfae040d34f5408ca505c0ded68f525dc26cf7a611f56e0b9af 

test:
  secret_key_base: a4082a4a9d8181c799d9803d88639d1e066b6413f20cf9545bf1c9169f272b6376ab3de7ac110925fb48026103b712416c6a45725056d36645d3d0c81fa91ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
